name: 'build'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: "michal-h21"
          password: ${{ secrets.PAT }}
          registry: ghcr.io
          repository: michal-h21/make4ht-action
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: latest
